name: Provision Azure Container Apps environment

on:
  push:
    tags: ["provison*.*.*"]
      
env:
  RESOURCE_GROUP_NAME: container-apps-example-rg

permissions:
  id-token: write
  contents: read
  pull-requests: write 

jobs:
  provision:
    name: Provision container apps env
    environment:
      name: provision
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Lint bicep file
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set bicep.use_binary_from_path=False
            az bicep install

            az bicep lint -f ./bicep/container-apps-env.bicep
  
      - name: Provision
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set bicep.use_binary_from_path=False
            az bicep install

            az deployment group create \
                -f ./bicep/container-apps-env.bicep \
                --name "container-apps-env--provision" \
                -g ${{ env.RESOURCE_GROUP_NAME }}
